# Copyright 2016 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Added soft-delete

Revision ID: 57baa245d5a7
Revises: 6bfd1c23aa18
Create Date: 2016-07-11 15:09:10.313138

"""

# revision identifiers, used by Alembic.
revision = '57baa245d5a7'
down_revision = '6bfd1c23aa18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computehost_allocations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('computehost_allocations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('computehost_extra_capabilities', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('computehost_extra_capabilities', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('computehost_reservations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('computehost_reservations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('computehosts', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('computehosts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('instance_reservations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('instance_reservations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('leases', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('leases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('reservations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('reservations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'deleted_at')
    op.drop_column('reservations', 'deleted')
    op.drop_column('leases', 'deleted_at')
    op.drop_column('leases', 'deleted')
    op.drop_column('instance_reservations', 'deleted_at')
    op.drop_column('instance_reservations', 'deleted')
    op.drop_column('events', 'deleted_at')
    op.drop_column('events', 'deleted')
    op.drop_column('computehosts', 'deleted_at')
    op.drop_column('computehosts', 'deleted')
    op.drop_column('computehost_reservations', 'deleted_at')
    op.drop_column('computehost_reservations', 'deleted')
    op.drop_column('computehost_extra_capabilities', 'deleted_at')
    op.drop_column('computehost_extra_capabilities', 'deleted')
    op.drop_column('computehost_allocations', 'deleted_at')
    op.drop_column('computehost_allocations', 'deleted')
    ### end Alembic commands ###
