# Copyright 2018 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add soft delete

Revision ID: 84b9a52f629c
Revises: b7bbd1021178
Create Date: 2018-11-20 14:59:38.410455

"""

# revision identifiers, used by Alembic.
revision = '84b9a52f629c'
down_revision = 'b7bbd1021178'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_allocations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('network_allocations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('network_reservations', sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('network_reservations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_reservations', 'deleted_at')
    op.drop_column('network_reservations', 'deleted')
    op.drop_column('network_allocations', 'deleted_at')
    op.drop_column('network_allocations', 'deleted')
    # ### end Alembic commands ###
